[project]
name = "argent-de-poche"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.5",
    "django-unfold>=0.49.1",
]
