# Generated by Django 5.1.5 on 2025-04-01 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_compte_total_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_compte', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur du compte'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Salaire'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.compte', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé à'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
