# Generated by Django 5.1.5 on 2025-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_compte_client_alter_compte_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='last_salary_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last salary payment'),
        ),
    ]
