# Generated by Django 5.1.5 on 2025-07-03 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_compte_last_salary_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='client',
            field=models.ForeignKey(help_text='Enfant ou bénéficiaire du compte.', on_delete=django.db.models.deletion.CASCADE, related_name='mon_compte', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur du compte'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='last_salary_payment',
            field=models.DateTimeField(blank=True, help_text='Date du dernier versement automatique du salaire.', null=True, verbose_name='Last salary payment'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='manager',
            field=models.ForeignKey(help_text='Parent ou responsable du compte.', on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='name',
            field=models.CharField(help_text='Nom du compte (ex: Prénom de l’enfant)', max_length=24, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='salary',
            field=models.FloatField(default=0, help_text='Montant du salaire hebdomadaire automatique.', verbose_name='Salaire'),
        ),
    ]
