# Generated by Django 5.1.5 on 2025-01-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('salary', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
